routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::Resource('blocks','BlockController');
Route::Resource('cities','CityController');
Route::Resource('clients','ClientController');
Route::Resource('restaurants','RestaurantController');
Route::Resource('categories','CategoryController');
Route::Resource('contact','ContactController');
Route::Resource('offers','OfferController');
Route::Resource('orders','OrderController');
Route::Resource('settings','SettingController');
Route::Resource('payments','PaymentMethodController');
Route::Resource('users','UserController');
Route::Resource('pays','PaymentController');
Route::get('get-change-password','UserController@getChangePassword');
Route::post('change-password','UserController@changePassword')->name('changePassword');
Route::get('active/{id}' , 'RestaurantController@active');
Route::get('disactive/{id}' , 'RestaurantController@disactive');

resources/views/pays/create.blade.php
@extends('layouts.app')
@inject('model','App\Models\Restaurant')
@section('page_title')
    العمليات المالية
@endsection
@section('content')

    <section class="content">
        @include('flash::message')
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">اضافه عمليه ماليه</h3>

            </div>
            <div class="box-body">
                {!! Form::model($model,[
                    'action' => 'PaymentController@store'
                ]) !!}
                @include('pays.form')
            </div>
        </div>
        <!-- /.box -->

    </section>
    <!-- /.content -->

@endsection

resources/views/pays/edit.blade.php
@extends('layouts.app')
@inject('restaurant','App\Models\Restaurant')
@inject('payment','App\Models\Payment')
@section('page_title')
    تعديل العمليات المالية
@endsection
@section('content')



    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">تعديل العمليات المالية</h3>

            </div>
            <div class="box-body">
                {!! Form::model($model,[
                    'action' => ['PaymentController@update',$model->id],
                    'method' => 'put'
                ]) !!}
                <div class="form-group">
                    <label for="name">المطعم</label>
                    {!! Form::select('restaurant_id',$restaurant->pluck('name','id'),null,[
                    'class'=>'form-control']) !!}
                    <label for="name"></label>
                    {!! Form::text('amount',null,[
                        'class' =>'form-control','placeholder'=>'المبلغ'
                    ]) !!}
                    <label for="name"></label>
                    {!! Form::text('note',null,[
                        'class' =>'form-control','placeholder'=>'بيان العمليه'
                    ]) !!}
                </div>
                @include('handler.errors')
                <div class="form-group">
                    <button class="btn btn-primary" type="submit">موافق</button>
                </div>
                {!! Form::close() !!}
            </div>

        </div>
        </div>
        <!-- /.box -->

    </section>
    <!-- /.content -->

@endsection

resources/views/pays/form.blade.php
<div>
    <div class="form-group">
        <label for="name">المطعم</label>
        {!! Form::select('restaurant_id',$model->pluck('name','id'),null,[
        'class'=>'form-control']) !!}
        <label for="name"></label>
        {!! Form::text('amount',null,[
            'class' =>'form-control','placeholder'=>'المبلغ'
        ]) !!}
        <label for="name"></label>
        {!! Form::text('note',null,[
            'class' =>'form-control','placeholder'=>'بيان العمليه'
        ]) !!}
    </div>
    @include('handler.errors')
    <div class="form-group">
        <button class="btn btn-primary" type="submit">موافق</button>
    </div>
    {!! Form::close() !!}
</div>

resources/views/pays/index.blade.php
@extends('layouts.app')
@section('page_title')
    العمليات الماليه
@endsection
@section('small_title')
    عرض العمليات
@endsection
@section('content')

    <!-- Main content -->
    <section class="content">
    @include('flash::message')
    <!-- Default box -->
        <div class="box">
            <div class="box-body">
                <a href="{{url(route('pays.create'))}}" class="btn btn-primary">
                    <i class="fa fa-plus "></i>  اضافه عمليه ماليه</a>
                @if(count([$records]))
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>اسم المطعم </th>
                                <th> المبلغ</th>
                                <th> بيان العمليه </th>
                                <th class="text-center">تعديل</th>
                                <th class="text-center">خذف</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($records as $record)
                                <tr>
                                    <td>{{$loop->iteration}}</td>
                                    <td>{{$record->restaurant->name}}</td>
                                    <td>{{$record->amount}}</td>
                                    <td>{{$record->note}}</td>
                                    <td class="text-center">
                                        <a href="{{url(route('pays.edit', $record->id))}}" class=" btn btn-success btn-xs">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                    </td>
                                    <td class="text-center">
                                        {!! Form::open([
                                            'action' => ['PaymentController@destroy',$record->id],
                                            'method' => 'delete'
                                        ]) !!}
                                        <button type="submit" class="delete_link btn btn-danger btn-xs">
                                            <i class="fa fa-trash-o">

                                            </i></button>
                                        {!! Form::close() !!}
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                @else
                    <div class="alert alert-danger" role="alert">
                        No Data
                    </div>
                @endif
            </div>
        </div>
    </section>
@endsection