routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::Resource('blocks','BlockController');
Route::Resource('cities','CityController');
Route::Resource('clients','ClientController');
Route::Resource('restaurants','RestaurantController');
Route::Resource('categories','CategoryController');
Route::Resource('contact','ContactController');
Route::Resource('offers','OfferController');
Route::Resource('orders','OrderController');
Route::Resource('settings','SettingController');
Route::Resource('payments','PaymentMethodController');
Route::Resource('users','UserController');
Route::Resource('pays','PaymentController');
Route::get('get-change-password','UserController@getChangePassword');
Route::post('change-password','UserController@changePassword')->name('changePassword');
Route::get('active/{id}' , 'RestaurantController@active');
Route::get('disactive/{id}' , 'RestaurantController@disactive');

app/models/Payment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Payment extends model {

	protected $table = 'payments';
	public $timestamps = true;
	protected $fillable = array('note', 'amount','restaurant_id');

	public function restaurant()
	{
		return $this->belongsTo('App\Models\Restaurant');
	}

}

app/Http/Controllers/PaymentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Payment;
use Illuminate\Http\Request;

class PaymentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $records = Payment::paginate(20);
        return view('pays.index', compact('records'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pays.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'restaurant_id' => 'required|exists:restaurants,id',
            'amount' => 'required|numeric',
            'note' => 'required'
        ];

        $message = [
            'restaurant_id.required' => 'Restaurant Is Required',
            'amount.required' => 'Amount Is Required',
            'note.required' => 'Note is Required'
        ];
        $this->validate($request,$rules,$message);

        $record = Payment::create($request->all());
        flash('Created!')->success();
        return redirect(route('pays.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = Payment::findOrFail($id);
        return view('pays.edit' , compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $record = Payment::findOrFail($id);
        $record->update($request->all());
        flash('Edited!')->success();
        return redirect(route('pays.index'));

        /**
         * Remove the specified resource from storage.
         *
         * @param int $id
         * @return \Illuminate\Http\Response
         */
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $record = Payment::findOrFail($id);
        $record->delete();
        flash('Deleted!')->error();
        return back();
    }
}

resources/views/payments/create.blade.php
@extends('layouts.app')
@inject('model','App\Models\PaymentMethod')
@section('page_title')
    انشاء طريقه الدفع
@endsection
@section('content')

    <section class="content">
        @include('flash::message')
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">انشاء طريقه الدفع</h3>
            </div>
            <div class="box-body">
                {!! Form::model($model,[
                    'action' => 'PaymentMethodController@store'
                ]) !!}
                @include('payments.form')
            </div>
        </div>
        <!-- /.box -->

    </section>
    <!-- /.content -->

@endsection

resources/views/payments/edit.blade.php
@extends('layouts.app')
@inject('payment','App\Models\PaymentMethod')
@section('page_title')
    تعديل طريقه الدفع
@endsection
@section('content')



    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">تعديل طريقه الدفع</h3>

            </div>
            <div class="box-body">
                {!! Form::model($model,[
                    'action' => ['PaymentMethodController@update',$model->id],
                    'method' => 'put'
                ]) !!}
                <div class="form-group">
                    @include('payments.form')
                </div>
                @include('handler.errors')
            </div>
        </div>
        <!-- /.box -->

    </section>
    <!-- /.content -->

@endsection

resources/views/payments/form.blade.php
<div>
    <div class="form-group">
        <label for="name">طرق الدفع</label>
        {!! Form::text('name',null,[
            'class' =>'form-control'
        ]) !!}
    </div>
    @include('handler.errors')
    <div class="form-group">
        <button class="btn btn-primary" type="submit">موافق</button>
    </div>
    {!! Form::close() !!}
</div>

resources/views/payments/index.blade.php
@extends('layouts.app')
@section('page_title')
    طرق الدفع
@endsection
@section('small_title')
    عرض الكل
@endsection
@section('content')


    <!-- Main content -->
    <section class="content">
    @include('flash::message')
    <!-- Default box -->
        <div class="box">
            <div class="box-body">
                <a href="{{url(route('payments.create'))}}" class="btn btn-primary">
                    <i class="fa fa-plus "></i>  اضف جديد</a>
                @if(count([$records]))
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>الاسم</th>
                                <th class="text-center">تعديل</th>
                                <th class="text-center">خذف</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($records as $record)
                                <tr>
                                    <td>{{$loop->iteration}}</td>
                                    <td>{{$record->name}}</td>
                                    <td class="text-center">
                                        <a href="{{url(route('payments.edit', $record->id))}}" class=" btn btn-success btn-xs">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                    </td>
                                    <td class="text-center">
                                        {!! Form::open([
                                            'action' => ['PaymentMethodController@destroy',$record->id],
                                            'method' => 'delete'
                                        ]) !!}
                                        <button type="submit" class="delete_link btn btn-danger btn-xs">
                                            <i class="fa fa-trash-o">

                                            </i></button>
                                        {!! Form::close() !!}
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                @else
                    <div class="alert alert-danger" role="alert">
                        No Data
                    </div>
                @endif
            </div>
        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->

@endsection